cluster-sidecar: "slurm-sidecar.py"
cluster-cancel: "scancel"
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
restart-times: 5
max-jobs-per-second: 5
max-status-checks-per-second: 5
local-cores: 1
latency-wait: 15
use-conda: True
use-singularity: True
jobs: 64
printshellcmds: True
keep-incomplete: True
notemp: True
rerun-incomplete: False
default-resources:
   - runtime=720
   - mem_mb=64000
   - partition=cpu-single
   - threads=1
