max_mins_per_step: 560

# Methods
methods:
    celloracle:
        modular: True
        k: 20
        thr_coaccess: 0.2
        ext: 500000
        fpr: 0.02
        blen: 200
        tfb_thr: 10
        a: 10
        p: 0.001
        n: 2000
    collectri:
        modular: False
    crema:
        modular: False
        ext: 500000
        site_extension: 200
        thr_fdr: 0.05
    dictys:
        modular: True
        ext: 500000
        device: 'cuda:0'
        n_p2g_links: 20
        use_p2g: False
        thr_score: 0.25
    directnet:
        modular: False
        ext: 500000
    dorothea:
        modular: False
    figr:
        modular: True
        ext: 500000
        thr_p2g_pval: 0.1
        ncres: 2
        cellK: 10
        dorcK: 10
        thr_score: 2
    granie:
        modular: True
        ext: 500000
        thr_fdr: 0.2
    grnboost:
        modular: False
    hummus:
        modular: False
        ext: 500000
    inferelator:
        modular: False
        ext: 500000
    pando:
        modular: True
        exclude_exons: 'TRUE'
        ext: 500000
        thr_corr: 0.05
        p_thresh: 0.1
        rsq_thresh: 0.05
        nvar_thresh: 2
        min_genes_per_module: 3
    pearson:
        modular: False
        mode: 'pearson'
        thr_r2: 0.1
    random:
        modular: False
        g_perc: 0.25
        scale: 1
        tf_g_ratio: 0.10
        w_size: 500000
        seed: 42
    scdori:
        modular: False
        ext: 500000
    scenic:
        modular: False
    scenicplus:
        modular: True
        ntopics: 50
        ext: 500000
    scgpt:
        modular: False
        batch_size: 8
        device: 'cuda:0'
        n_hvg: 8192
        min_score: 0.9
    scmtni:
        modular: False
        ext: 500000
    spearman:
        modular: False
        mode: 'spearman'
        thr_r2: 0.1

baselines: ['collectri', 'dorothea', 'grnboost', 'scenic', 'pearson', 'spearman', 'scgpt', 'random']
mm10_methods: ['celloracle', 'dictys', 'figr', 'scenicplus', 'collectri', 'dorothea', 'grnboost', 'scenic', 'pearson', 'spearman', 'random']

colors:
    nets:
        celloracle: '#1e76b4'
        crema: '#aec6e7'
        dictys: '#ff7f0e'
        directnet: '#ffba78'
        figr: '#2ca02c'
        granie: '#97de8a'
        hummus: '#d52727'
        inferelator: '#ff9796'
        pando: '#9467bc'
        scdori: '#c4afd4'
        scenicplus: '#8c554a'
        scmtni: '#c49c94'
        collectri: '#e276c1'
        dorothea: '#f6b6d2'
        grnboost: '#bcbd22'
        scenic: '#dada8d'
        pearson: '#16becf'
        spearman: '#9edae4'
        scgpt: '#7e7e7e'
        random: 'black'

dts_names:
    lung: Lung
    embryo: Embryo
    skin: Skin
    heart: Heart
    pbmc10k: PBMC
    epalate: Palate
    kidney: Kidney
    eye: Eye
    pitupair: Pituitary
    breast: Breast
    reprofibro: Reprog. Fibro
    brain: Brain

dbs_names:
  eqtlcatalogue: "eQTL Catalogue"
  blacklist: "ENCODE Blacklist"
  encode: "ENCODE CREs"
  gwascatalogue: "GWAS Catalog"
  promoters: "Promoters"
  zhang21: "Zhang21"
  phastcons: "phastCons"
  chipatlas: "ChIP-Atlas"
  remap2022: "ReMap 2022"
  unibind: "UniBind"
  knocktf: "KnockTF"
  hpa: "Human Protein Atlas (HPA)"
  tfmdb: "TF-Marker"
  europmc: "Europe PMC"
  intact: "IntAct"
  reac: Reactome
  hall: Hallmarks
  kegg: KEGG
  prog: PROGENy
  gtf: G ~ TF
  cretf: CRE ~ TF
    

class_names:
  genom: Genomic
  mech: Mechanistic
  pred: Predictive
  prior: Prior

method_names:
  celloracle: CellOracle
  collectri: CollecTRI
  crema: CREMA
  dictys: Dictys
  directnet: DirectNet
  dorothea: DoRothEA
  figr: FigR
  granie: GRaNIE
  grnboost: GRNBoost2
  hummus: HuMMuS
  inferelator: Inferelator
  pando: Pando
  pearson: Pearson
  random: Random
  scdori: scDoRI
  scenic: SCENIC
  scenicplus: SCENIC+
  scgpt: scGPT
  scmtni: scMTNI
  spearman: Spearman

# Datasets
dts:
    brain:
        organism: 'hg38'
        url:
            full_dataset: 'https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE193688'
            annot: 'https://heibox.uni-heidelberg.de/f/05637a872a384155a951/?dl=1'
        samples:
            ['C4361', 'C5410', 'C4814', 'C4660', 'C4176']  # Filter for Aged Females
        cases:
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
    breast:
        organism: 'hg38'
        url:
            tar: 'https://datasets.cellxgene.cziscience.com/32e9543f-f40f-4698-b877-8c7a67a5e266-fragment.tsv.bgz'
            anndata: 'https://datasets.cellxgene.cziscience.com/ab8821d8-7548-4592-b83e-f308ad36b312.h5ad'
        samples:
            ['ID13', 'ID14']  # Filter for Asian American Females
        cases:
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
    embryo:
        organism: 'hg38'
        url:
            tar: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE218314&format=file'
            rna: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE218314&format=file&file=GSE218314%5Fhuman%5Fmodel%5FRNA%5Fmatrix%2Erds%2Egz'
            ann: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE218314&format=file&file=GSE218314%5Fhuman%5Fmodel%5Fmetadata%2Ecsv%2Egz'
        samples:
            ['D4', 'D6', 'D8']
        cases:
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
    eye:
        organism: 'hg38'
        url:
            tar: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE196235&format=file'
            ann: 'https://drive.google.com/uc?export=download&id=19C8I3ZwtI-WKXOj_RSF_KoY4ySWoPl-5'
        samples:
            ['LGS1OD', 'LGS3OD']  # Filter for Females
        cases:
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
    kidney:
        organism: 'hg38'
        url:
            tar: 'https://zenodo.org/records/8029990/files'
            h5se: 'https://zenodo.org/records/8029990/files/raw_snATAC_and_snRNA_human_kidney.h5Seurat?download=1'
        samples:
            ['20210804A', '20210917A']  # Downsample to two samples
        cases:
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
    lung:
        organism: 'hg38'
        url:
            geo: 'https://www.ncbi.nlm.nih.gov/geo/download'
            annot: 'https://drive.google.com/uc?export=download&id=1Ky-jPYD6eWQ1RELzHF9VJIbEZdeALExw'
        samples:
            ['FN1', 'FN2']  # Filter for Non-Smoker Females # 'FN3', 'FN4'
        gex_geoids:
            ['GSM7729458%5FFN1', 'GSM7729459%5FFN2'] # 'GSM7729460%5FFN3', 'GSM7729461%5FFN4'
        atac_geoids:
            ['GSM7729474%5FFN1', 'GSM7729475%5FFN2'] # 'GSM7729476%5FFN3', 'GSM7729477%5FFN4'
        cases:
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
    heart:
        organism: 'hg38'
        url:
            tar: 'https://cellgeni.cog.sanger.ac.uk/heartcellatlas/v2/fragments.tar'
            anndata: 'https://cellgeni.cog.sanger.ac.uk/heartcellatlas/v2/Global_raw.h5ad'
            annot: 'https://cellgeni.cog.sanger.ac.uk/heartcellatlas/v2/Adult_Peaks.h5ad'
        samples:
            ['HCAHeart9508821', 'HCAHeart9508819', 'HCAHeart9917173']  # Filter for LV and Male
        cases:
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
    fakepitupair:
        organism: 'hg38'
        samples:
            ['smpl']
        cases:
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
    pbmc10k:
        organism: 'hg38'
        url:
            matrix: 'https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k_filtered_feature_bc_matrix.h5'
            atac_frags: 'https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k_atac_fragments.tsv.gz'
        samples:
            ['smpl']
        cases:
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
            test:
                celltypes: "Naive B;Intermediate B;Memory B"
                n_hvg: 2048
                n_hvr: 8192
    pitunpair:
        organism: 'hg38'
        url:
            atac_frags: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM5391768&format=file&file=GSM5391768%5FHFA1P%5Ffragments%2Etsv%2Egz'
            peaks: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM5391768&format=file&file=GSM5391768%5FHFA1P%5Ffiltered%5Fpeak%5Fbc%5Fmatrix%2Eh5'
            rna_mtx: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM5391775&format=file&file=GSM5391775%5FHF1P%5Ffiltered%5Ffeature%5Fbc%5Fmatrix%2Eh5'
            annot: 'https://heibox.uni-heidelberg.de/f/d36511f7f94947859564/?dl=1'
        samples:
            ['smpl']
        cases:
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
    pitupair:
        organism: 'hg38'
        url:
            frags: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM5391776&format=file&file=GSM5391776%5FHF1M%2DCryo%5Fatac%5Ffragments%2Etsv%2Egz'
            gex: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM5391776&format=file&file=GSM5391776%5FHF1M%2DCryo%5Ffiltered%5Ffeature%5Fbc%5Fmatrix%2Eh5'
            annot: 'https://heibox.uni-heidelberg.de/f/de56839fd8b24d0aba4a/?dl=1'
        samples:
            ['smpl']
        cases:
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
    reprofibro:
        organism: 'hg38'
        url:
            tar: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE242419&format=file'
            barcodes: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE242419&format=file&file=GSE242419%5Fmultiome%2EATAC%2ERNA%2Ebarcode%2Emap%2Etsv%2Egz'
            genes: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE242419&format=file&file=GSE242419%5Fmultiome%5Fgenes%2Etsv%2Egz'
            annot: 'https://zenodo.org/records/8313962/files/multiome.zip?download=1'
        samples:
            ['D1M', 'D2M']
        cases:
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
                root: 'Fibroblast-like'
    skin:
        organism: 'hg38'
        url:
            tar: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE207335&format=file'
            ann: 'https://drive.google.com/uc?export=download&id=1K9vkCBNP0HugUqStYYevlVwd-lTsGllp'
        samples:
            ['S1', 'S2']
        cases:
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
    epalate:
        organism: 'mm10'
        url:
            gdrive: 'https://drive.usercontent.google.com/download?id=1VfIQQ4Uy6rf9HEaUbHnC3lpfsSmpdjrX&export=download&confirm=t'
            frag_E1401: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE218576&format=file&file=GSE218576%5FB6E14%2D0%2D1%5Fatac%5Ffragments%2Etsv%2Egz'
            frag_tbi_E1401: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE218576&format=file&file=GSE218576%5FB6E14%2D0%2D1%5Fatac%5Ffragments%2Etsv%2Egz%2Etbi%2Egz'
            h5_E1401: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE218576&format=file&file=GSE218576%5FB6E14%2D0%2D1%5Ffiltered%5Ffeature%5Fbc%5Fmatrix%2Eh5'
            frag_E1251: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE218576&format=file&file=GSE218576%5FB6E12%2D5%2D1%5Fatac%5Ffragments%2Etsv%2Egz'
            frag_tbi_E1251: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE218576&format=file&file=GSE218576%5FB6E12%2D5%2D1%5Fatac%5Ffragments%2Etsv%2Egz%2Etbi%2Egz'
            h5_E1251: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE218576&format=file&file=GSE218576%5FB6E12%2D5%2D1%5Ffiltered%5Ffeature%5Fbc%5Fmatrix%2Eh5'
        samples:
            ['E1401', 'E1251']
        cases:
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536


stab_datasets: ['pitupair']
modular_datasets: ['pitupair']
nocombs_datasets: ['pitupair', 'pitunpair', 'fakepitupair']
big_datasets: ['brain', 'heartatlas']

# Databases
dbs:
    ont:
        bto: 'https://service.tib.eu/ts4tib/api/ontologies/bto/download'
    hg38:
        gen:
            lambert: 'http://humantfs.ccbr.utoronto.ca/download/v_1.01/TF_names_v_1.01.txt'
            scenic: 'https://resources.aertslab.org/cistarget/tf_lists/allTFs_hg38.txt'
        prt:
            knocktf:
                meta: 'https://zenodo.org/record/7035528/files/knockTF_meta.csv?download=1'
                diff: 'https://zenodo.org/record/7035528/files/knockTF_expr.csv?download=1'
        gst:
            hall: 'https://data.broadinstitute.org/gsea-msigdb/msigdb/release/2024.1.Hs/h.all.v2024.1.Hs.symbols.gmt'
            kegg: 'https://data.broadinstitute.org/gsea-msigdb/msigdb/release/2024.1.Hs/c2.cp.kegg_legacy.v2024.1.Hs.symbols.gmt'
            reac: 'https://data.broadinstitute.org/gsea-msigdb/msigdb/release/2024.1.Hs/c2.cp.reactome.v2024.1.Hs.symbols.gmt'
            prog: 'https://github.com/saezlab/progeny/raw/master/data/model_human_full.rda'
        pkn:
            collectri: 'https://zenodo.org/records/8192729/files/CollecTRI_regulons.csv'
            dorothea: 'https://github.com/saezlab/dorothea/raw/master/data/dorothea_hs.rda'
        tfm:
            hpa: 'https://www.proteinatlas.org/download/proteinatlas.tsv.zip'
            tfmdb: 'https://zenodo.org/records/5574651/files/download_TFMarker.csv?download=1'
        tfp:
            europmc: None
            intact: 'https://ftp.ebi.ac.uk/pub/databases/intact/current/psimitab/intact.zip'
        tfb:
            chipatlas:
                meta: 'https://chip-atlas.dbcls.jp/data/metadata/experimentList.tab'
                url: 'https://chip-atlas.dbcls.jp/data/hg38/assembled/Oth.ALL.50.{chipatlas_tf}.AllCell.bed'
            remap2022:
                meta: 'https://remap.univ-amu.fr/storage/remap2022/biotypes/remap2022_hsap_biotypes.xlsx'
                url: 'https://remap.univ-amu.fr/storage/remap2022/hg38/MACS2/remap2022_nr_macs2_hg38_v1_0.bed.gz'
            unibind:
                url: 'https://unibind.uio.no/static/data/20220914/bulk_Robust/Homo_sapiens/hg38_compressed_TFBSs.bed.gz'
        cre:
            blacklist: 'https://github.com/Boyle-Lab/Blacklist/raw/61a04d2c5e49341d76735d485c61f0d1177d08a8/lists/hg38-blacklist.v2.bed.gz'
            encode: 'https://downloads.wenglab.org/Registry-V3/GRCh38-cCREs.bed'
            gwascatalogue: 'https://www.ebi.ac.uk/gwas/api/search/downloads/alternative'
            phastcons: 'https://github.com/quadbio/Pando/raw/main/data/phastConsElements20Mammals.UCSC.hg38.RData'
            promoters: None
            zhang21: 'https://data.mendeley.com/api/datasets/dr2z4jbcx3/draft/files/91f93222-1a24-49a5-92e3-d9105ec53f91?a=758c37e5-4832-4c91-af89-9a1a83a051b3'
        c2g:
            eqtlcatalogue:
                meta: 'https://raw.githubusercontent.com/eQTL-Catalogue/eQTL-Catalogue-resources/refs/heads/master/tabix/tabix_ftp_paths.tsv'
                url: 'http://ftp.ebi.ac.uk/pub/databases/spot/eQTL/susie/{eqtl_smpl_grp}/{eqtl_tiss}/{eqtl_tiss}.credible_sets.tsv.gz'
                thr_pval: 1e-5
    mm10:
        gen:
            scenic: 'https://resources.aertslab.org/cistarget/tf_lists/allTFs_mm.txt'
            lambert: 'https://raw.githubusercontent.com/gifford-lab/ReprogrammingRecovery/main/data/mouse_ensemble_tfs_from_lambertetal_isyes.unique.txt'
        cre:
            blacklist: 'https://github.com/Boyle-Lab/Blacklist/raw/master/lists/mm10-blacklist.v2.bed.gz'
            encode: 'https://downloads.wenglab.org/V3/mm10-cCREs.bed'
            phastcons: "https://hgdownload.soe.ucsc.edu/goldenPath/mm10/database/phastConsElements60way.txt.gz"
        gst:
            hall: "https://data.broadinstitute.org/gsea-msigdb/msigdb/release/2025.1.Mm/mh.all.v2025.1.Mm.symbols.gmt"
            reac: "https://data.broadinstitute.org/gsea-msigdb/msigdb/release/2025.1.Mm/m2.cp.reactome.v2025.1.Mm.symbols.gmt"
            prog: "https://github.com/saezlab/progeny/raw/master/data/model_mouse_full.rda"
        tfb:
            chipatlas:
                meta: "https://chip-atlas.dbcls.jp/data/metadata/experimentList.tab"
                url: "https://chip-atlas.dbcls.jp/data/mm10/assembled/Oth.ALL.50.{chipatlas_tf}.AllCell.bed"
            remap2022:
                meta: 'https://remap.univ-amu.fr/storage/remap2022/biotypes/remap2022_mmus_biotypes.xlsx'
                url:  'https://remap.univ-amu.fr/storage/remap2022/mm10/MACS2/remap2022_nr_macs2_mm10_v1_0.bed.gz'
            unibind:
                url: 'https://unibind.uio.no/static/data/20220914/bulk_Robust/Mus_musculus/mm10_compressed_TFBSs.bed.gz'
        pkn:
            collectri: 'https://drive.google.com/uc?export=download&id=1EEIT_PDGtAMG1O9L_hV4F1s1Ijep4lDq'
            dorothea: 'https://drive.google.com/uc?export=download&id=1rZynSkaXUqC7zut6ewvLTXWz_T2Xm1TQ'
        prt:
            knocktf:
                meta: None
                diff: None
tfb_max_psize: 750
cre_prom_size: 1000
topo_min_prop: 0.33

# Simulated data
zenodo_id: 17872739
